### ISSUE TITLE
ReferenceError: result is not defined

### ISSUE THREAD

**Issue by tcastelli** [signaturit/nodejs-sdk#2]
ReferenceError: result is not defined on signaturit.js:32:29

I think there is a typo on 

``` javascript
function (error, response, body) {
        if (error) {
            deferred.reject(result);
        } else {
            deferred.resolve(body);
        }
    }
```

result does not exist

**Comment by lales12** [comment]
Hi tcastelli.
Thanks for your issue, this is fixed on later comits.
In short we create a new version.
