### ISSUE TITLE
Sugerencia: capturar errores en lectura de ficheros con fs

### ISSUE THREAD

**Issue by mizoRC** [signaturit/nodejs-sdk#4]
Os añado esta issue como sugerencia para capturar errores con la librería fs que usáis en vuestro sdk para leer los archivos que se emplean para generar la petición de "Create signature".
Normalmente el error suele ser del desarrollador, que indica una ruta relativa incorrecta, pero no estaría demás que se capturase dicho error.

Al enviar la petición siempre me devolvía un error con descripción "undefined" que era provocado por ese motivo, entonces en local he añadido 

```
files.forEach(function(filePath, i) {
       var stream = fs.createReadStream(filePath);
        form.append(
           'files[' + i + ']',
            stream
        );
        stream.on('error', function (error) {console.log("Caught", error);});
})
```

en las líneas 75-80 ,para comprobar que efectivamente estaba poniendo una ruta incorrecta.

Es solo una sugerencia para evitar problemas de este tipo, ya que el mensaje de error es muy confuso. Espero que os sea de ayuda.

**Comment by thgh** [comment]
Agree, the docs say you should pass an empty string `''`, but this will always error.
Empty array works: `[]`
